build: Fix ExEx build due to missing forge build outputs [SEQ-40] (#19)
* chore: Add build contracts step

* fix: Switch to more robust forge command detection

The prior version was working on zsh on Mac but failing on bash on Ubuntu. This version works on both machines

* fix: Handle corrupted forge installation

* fix: Fix segmentation fault check

* fix: Catch error instead of checking for segmentation fault text

* chore: Check the build subcommand specifically

* chore: Also source .bashrc according to Foundry instructions

* fix: Fix command sourcing option

* chore: Echo contract completion

Co-authored-by: Daniil R <daniil@syndicate.io>

---------

Co-authored-by: Daniil R <daniil@syndicate.io>

diff --git a/reth-and-exexs/Makefile b/reth-and-exexs/Makefile
--- a/reth-and-exexs/Makefile
+++ b/reth-and-exexs/Makefile
@@ -30,9 +30,23 @@ help: ## Display this help.
 
 ##@ Build
 
-.PHONY: install
-install: ## Build and install the op-reth binary under `~/.cargo/bin`.
+.PHONY: build-op-reth-syn
+build-op-reth-syn: ## Build and install the op-reth binary under `~/.cargo/bin`.
 	cargo install --path . --bin op-reth-syn --force --locked \
 		--features "$(FEATURES)" \
 		--profile "$(PROFILE)" \
 		$(CARGO_INSTALL_EXTRA_FLAGS)
+
+.PHONY: build-contracts
+build-contracts: ## Build contracts using forge. Install Foundry if the forge command is not found or is corrupted.
+	@if [ -z "$$(which forge)" ]; then \
+		echo "Forge not found. Installing Foundry..."; \
+		curl -L https://foundry.paradigm.xyz | bash && bash -c "source ~/.bashrc && foundryup"; \
+	fi
+	@forge build --help > /dev/null 2>&1 || (echo "Forge is corrupted. Reinstalling Foundry..." && curl -L https://foundry.paradigm.xyz | bash && bash -c "source ~/.bashrc && foundryup")
+	cd ../contracts && forge build
+  echo "build-contracts Complete"
+##@ Custom Build
+
+.PHONY: install
+install: build-contracts build-op-reth-syn ## Run custom build steps.
