build: Add `make test` step and clean up Makefile (#24)
* build: Add tests

* chore: Echo when installation is complete

* chore: Add additional instructions to run a node

* chore: Move install-foundry into its own step

diff --git a/reth-and-exexs/Makefile b/reth-and-exexs/Makefile
--- a/reth-and-exexs/Makefile
+++ b/reth-and-exexs/Makefile
@@ -30,6 +30,15 @@ help: ## Display this help.
 
 ##@ Build
 
+.PHONY: install-foundry
+install-foundry: ## Install Foundry if the forge command is not found or is corrupted.
+	@if [ -z "$$(which forge)" ]; then \
+		echo "Forge not found. Installing Foundry..."; \
+		curl -L https://foundry.paradigm.xyz | bash && bash -c "source ~/.bashrc && foundryup"; \
+	fi
+	@forge build --help > /dev/null 2>&1 || (echo "Forge is corrupted. Reinstalling Foundry..." && curl -L https://foundry.paradigm.xyz | bash && bash -c "source ~/.bashrc && foundryup")
+	@echo "Foundry is installed and ready to use."
+
 .PHONY: build-op-reth-syn
 build-op-reth-syn: ## Build and install the op-reth binary under `~/.cargo/bin`.
 	cargo install --path . --bin op-reth-syn --force --locked \
@@ -38,15 +47,17 @@ build-op-reth-syn: ## Build and install the op-reth binary under `~/.cargo/bin`.
 		$(CARGO_INSTALL_EXTRA_FLAGS)
 
 .PHONY: build-contracts
-build-contracts: ## Build contracts using forge. Install Foundry if the forge command is not found or is corrupted.
-	@if [ -z "$$(which forge)" ]; then \
-		echo "Forge not found. Installing Foundry..."; \
-		curl -L https://foundry.paradigm.xyz | bash && bash -c "source ~/.bashrc && foundryup"; \
-	fi
-	@forge build --help > /dev/null 2>&1 || (echo "Forge is corrupted. Reinstalling Foundry..." && curl -L https://foundry.paradigm.xyz | bash && bash -c "source ~/.bashrc && foundryup")
+build-contracts: install-foundry ## Build contracts using forge.
 	cd ../contracts && forge build
 	@echo "Contract compilation complete"
+
+.PHONY: test
+test: build-contracts ## Run tests after building the contracts.
+	cargo test --all
+	@echo "Tests complete"
+
 ##@ Custom Build
 
 .PHONY: install
-install: build-contracts build-op-reth-syn ## Run custom build steps.
+install: build-contracts build-op-reth-syn ## Run build steps.
+	@echo "Install complete. You can now run op-reth-syn from your terminal."
