chore: Add op-clean command

diff --git a/.devcontainer/justfile b/.devcontainer/justfile
--- a/.devcontainer/justfile
+++ b/.devcontainer/justfile
@@ -6,7 +6,14 @@ export PATH := foundry_path
 
 # Clone the Optimism repository
 op-clone:
-    git clone --branch v1.9.4 --single-branch --depth 1 https://github.com/ethereum-optimism/optimism.git ~/optimism || echo skipping clone 
+    # Version v.1.9.4 currently breaks with the error `t=2024-10-22T23:38:03+0000 lvl=crit msg="Application failed" message="failed to fetch startBlock from SystemConfig: failed to call startBlock: failed to unpack result: failed to unpack data: abi: attempting to unmarshal an empty string while arguments are expected"`
+    # Update to the latest release once this is fixed
+    git clone --branch v1.9.3 --single-branch --depth 1 https://github.com/ethereum-optimism/optimism.git ~/optimism || echo skipping clone 
+
+op-clean:
+    rm -rf ~/optimism
+    just op-clone
+    @echo "OP Devnet cleaned and re-cloned"
 
 go-install:
     go install /workspaces/metabased-rollup/op-translator
@@ -46,6 +53,7 @@ create-aliases:
             echo "# Local Devnet aliases" >> "$rc_file"
             echo "alias op-up='just -f {{justfile()}} op-devnet-up'" >> "$rc_file"
             echo "alias op-down='just -f {{justfile()}} op-devnet-down'" >> "$rc_file"
+            echo "alias op-clean='just -f {{justfile()}} op-clean'" >> "$rc_file"
             echo "alias go-install='just -f {{justfile()}} go-install'" >> "$rc_file"
             echo "Aliases created in $rc_file"
         else
