update workflow

diff --git a/.github/workflows/contracts-check.yaml b/.github/workflows/contracts-check.yaml
--- a/.github/workflows/contracts-check.yaml
+++ b/.github/workflows/contracts-check.yaml
@@ -26,8 +26,6 @@ jobs:
       # Enable fail-fast to stop the job immediately if any step fails
       # This helps catch issues early and prevents wasting CI resources
       fail-fast: true
-      matrix:
-        contract-dir: ["metabased-translator/contracts", "metabased-contracts"]
 
     name: ${{ matrix.contract-dir }} Check
     runs-on: ubuntu-latest
@@ -67,16 +65,8 @@ jobs:
       # --force flag to clear the cache and artifacts folder and recompile
       # -C to create bindings only for a specific directory
 
-      - name: Check Rust contract bindings for metabased-translator
-        if: matrix.contract-dir == 'metabased-translator/contracts'
+      - name: Check Rust contract bindings
         run: |
-          mv ../contracts-bindigs/src/arbitrum old/
-          make create-arbitrum-contract-bindings
-          diff -r -q old/ ../contract-bindings/src/arbitrum || (echo "Error: Rust contract bindings are out of date. Please run 'make -C metabased-translator create-contract-bindings' to update them." && exit 1)
-
-      - name: Check Rust contract bindings for metabased-contracts
-        if: matrix.contract-dir == 'metabased-contracts'
-        run: |
-          forge bind --alloy --force -C ./sequencing-modules
-          mv out/bindings/src/lib.rs out/bindings/src/mod.rs
-          diff -r -q out/bindings/src ../metabased-translator/contract-bindings/src/metabased || (echo "Error: Rust contract bindings are out of date. Please run 'make -C metabased-translator create-contract-bindings' to update them." && exit 1)
+          mv ../contracts-bindigs/ old/
+          make create-contract-bindings
+          diff -r -q old/ ../contract-bindings/ || (echo "Error: Rust contract bindings are out of date. Please run 'make -C metabased-translator create-contract-bindings' to update them." && exit 1)
