update github action

diff --git a/.github/workflows/contracts-check.yaml b/.github/workflows/contracts-check.yaml
--- a/.github/workflows/contracts-check.yaml
+++ b/.github/workflows/contracts-check.yaml
@@ -27,7 +27,7 @@ jobs:
       # This helps catch issues early and prevents wasting CI resources
       fail-fast: true
       matrix:
-        contract-dir: ['metabased-translator/contracts', 'metabased-contracts']
+        contract-dir: ["shared/contracts", "metabased-contracts"]
 
     name: ${{ matrix.contract-dir }} Check
     runs-on: ubuntu-latest
@@ -66,18 +66,17 @@ jobs:
       # when generating the bindings:
       # --force flag to clear the cache and artifacts folder and recompile
       # -C to create bindings only for a specific directory
-        
-      - name: Check Rust contract bindings for metabased-translator
-        if: matrix.contract-dir == 'metabased-translator/contracts'
+
+      - name: Check Rust contract bindings for shared contratcs
+        if: matrix.contract-dir == 'shared/contracts'
         run: |
           forge bind --alloy --force
           mv out/bindings/src/lib.rs out/bindings/src/mod.rs
-          diff -r -q out/bindings/src ../contract-bindings/src/arbitrum || (echo "Error: Rust contract bindings are out of date. Please run 'make -C metabased-translator create-contract-bindings' to update them." && exit 1)
+          diff -r -q out/bindings/src ../contract-bindings/src/arbitrum || (echo "Error: Rust contract bindings are out of date. Please run 'make -C shared create-contract-bindings' to update them." && exit 1)
 
       - name: Check Rust contract bindings for metabased-contracts
         if: matrix.contract-dir == 'metabased-contracts'
         run: |
           forge bind --alloy --force -C ./sequencing-modules --libraries src/use-cases/dream/RLP/RLPTxDecoder.sol:RLPTxDecoder:0x1234567890123456789012345678901234567890
           mv out/bindings/src/lib.rs out/bindings/src/mod.rs
-          diff -r -q out/bindings/src ../metabased-translator/contract-bindings/src/metabased || (echo "Error: Rust contract bindings are out of date. Please run 'make -C metabased-translator create-contract-bindings' to update them." && exit 1)
-          
+          diff -r -q out/bindings/src ../shared/contract-bindings/src/metabased || (echo "Error: Rust contract bindings are out of date. Please run 'make -C shared create-contract-bindings' to update them." && exit 1)
