CI fix

diff --git a/.github/workflows/contracts-check.yaml b/.github/workflows/contracts-check.yaml
--- a/.github/workflows/contracts-check.yaml
+++ b/.github/workflows/contracts-check.yaml
@@ -60,12 +60,18 @@ jobs:
           forge test -vvv
         id: test
 
-      # when generating the Rust bindings below:
-      # --force flag to clear the cache and artifacts folder and recompile
-      # -C to create bindings only for a specific directory
+      # GO and abigen are needed to generate the Go bindings for the withdrawal contract
+      - name: Install Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: '1.21'
+
+      - name: Install abigen
+        run: |
+          go install github.com/ethereum/go-ethereum/cmd/abigen@latest
 
       - name: Check Rust contract bindings for synd-contracts
+        working-directory: "."
         run: |
-          forge bind --alloy --force
-          mv out/bindings/src/lib.rs out/bindings/src/mod.rs
-          diff -r -q out/bindings/src ../shared/contract-bindings/src/synd || (echo "Error: Rust contract bindings are out of date. Please run 'make -C shared create-contract-bindings' to update them." && exit 1)
+          make -C shared create-contract-bindings
+          git diff --quiet || (echo "Error: Rust contract bindings are out of date. Please run 'make -C shared create-contract-bindings' to update them." && exit 1)
